### ISSUE TITLE
Upgrade Flask-SQLAlchemy before db init

### ISSUE THREAD

**Issue by mlinkenmeyer** [learn-co-curriculum/python-p4-v2-building-get-api#5]
### Canvas Link

https://learning.flatironschool.com/courses/6813/assignments/257025?module_item_id=608033

### Concern

The command flask db init doesn't work. 

You have to first run this command:
pip install Flask-SQLAlchemy --upgrade

### Additional Context

Building a GET API : Code-Along
https://learning.flatironschool.com/courses/6813/assignments/257025?module_item_id=608033

**Comment by linda-seiter** [comment]
Pipfile updated
